/**
 * The port, held against what the Python parser says about the same bytes.
 *
 * This is the test that makes the port provable rather than plausible. The other test files state
 * the same claims twice, once per language, and two statements written from one understanding can
 * be wrong in the same way. A vector generated by one implementation and asserted by the other
 * cannot be: every field of it is a number the other side has to reproduce, including the ones
 * nobody thought to write a test about.
 *
 * Generate or refresh with `tools/golden.py --write`. The vectors live in the lab directory
 * because they describe private dumps, so these tests skip cleanly on a bare checkout, like every
 * other image-backed test here.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';

import { goldenVector, load, skipUnlessGolden } from '@harmony/lab';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parse, summary } from '../src/index.ts';

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..', '..');

/**
 * Same list as `CONTAINERS` in `tools/golden.py`, including the samples that are not somebody's
 * configuration. An implementation can agree on the ordinary cases and diverge on the degenerate
 * ones: the empty 0xFEED frame only occurs in a safe mode config.
 *
 * The list is written out rather than derived, because a test should say what it covers. **But the
 * comment that used to stand here, saying duplication is what stops a sample being lost, was
 * exactly wrong**: `h525_config_2` had been on the Python side and not on this one, so its
 * comparison had never run and nothing said so. The last test in this file compares the two lists
 * now, so the duplication is checked instead of trusted.
 */
const CONTAINERS = [
  'one_safemode',
  'one34_region2',
  'h700_gspm',
  'h600_safemode_gspm',
  'h650_safemode_gspm',
  'one_config',
  'one_config_unprogrammed',
  'h600_config',
  'h700_config',
  'h700_config_2',
  'h525_config',
  'h525_config_2',
  'arch8_config_a',
  'arch8_config_b',
  'arch8_config_c',
  'arch8_config_d',
  'h525_safemode_ahcm',
  // The same container in situ, at blob offset 0x8000 of the 64 KiB external firmware region it was
  // cut out of. A deliberate duplicate: it is what checks the cut was made in the right place, since
  // both parses have to agree about the base, the end address and every check. Section 118.
  'h525_external_firmware',
  'one_spare_before_sync',
  'one_spare_after_sync',
  // The third state of that unit, section 155, and the richest known answer sample: a real five
  // device setup built by MyHarmony from an account whose contents we can ask for.
  'one_spare_myharmony',
  // The fourth state of that unit, read on 30 August 2026 because the write rehearsal refused
  // against all three above. It populates base slot 16, which makes it the first sample read **off a
  // remote** where the two implementations of that reader are compared; the others that populate it
  // are files the live service compiled.
  'one_spare_20260830',
  // The same unit after the first write, section 222. Its vector duplicates the one above on
  // purpose: the write reproduced the bytes that were there, so a difference would be a finding.
  'one_spare_after_first_write',
  // The two configs Logitech compiled to a specification we wrote, section 132: the only samples
  // whose devices and activities were chosen before the bytes existed, so a disagreement between the
  // two implementations about them would be a disagreement about a known answer.
  'calibration_one',
  'calibration_h600',
  // The first config anywhere to populate base slot 16, so the only vector where the two
  // implementations of that reader are compared on a record rather than on an empty list.
  'calibration_favchannels',
  // The second to populate it, and the one that shows the section does not carry every favourite:
  // two of its five spell the number out one digit code at a time. Section 156.
  'calibration_favzero',
  // The largest sample anywhere here, section 165: fifteen appliances chosen so that every protocol
  // family in Logitech's catalogue the corpus could not settle appears in it. This is the first and
  // largest of the three compiled samples the rhythm table's thirty two non corpus entries are measured
  // off, so a disagreement about it is a disagreement about the table. The count used to be given as
  // eighteen off this file alone, which was true when it was the only one.
  'compiled_protocols',
  // The second of the pair, ten more appliances chosen for the families the first did not reach.
  'compiled_protocols_2',
  // The third, an hour later: the four the second had no room for, plus the appliance whose account
  // name the rebuilt capture of the first could not recover, which is what put one entry back to
  // being confirmed by two routes.
  'compiled_protocols_3',
  // The phase 7 pair, section 174: the calibration account compiled without and with the
  // television the composer adds. The after container is the one the composer is compared to.
  'phase7_before', 'phase7_after',
  // The Harmony 350, arch 16. Here so both codecs are compared on an architecture neither was
  // written for, and deliberately not in any corpus wide population, section 194.
  'h350_config',
  // The arch 8 safe mode container, found inside the firmware image itself at blob offset 0xE000
  // rather than in a file of its own. Section 114.
  'arch8_code_880',
  'arch8_code_885',
  // An 885 user config, and the first arch 10 container, whose four failing checks the vector
  // records rather than hides. Sections 113 and 115.
  'arch8_config_880',
  'arch8_config_885',
  // The Harmony 895, the third arch 10 container and the only one with a known answer. In the
  // vectors rather than in any corpus wide population, exactly like the 890s and for the same
  // reason: every arch 10 reader is gated. What the comparison is for here is the framing, which
  // does read, so a divergence between the two codecs about a container nothing else can read
  // would otherwise be invisible. Section 178.
  'h895_config',
  'h890_config',
  'h890_config_2',
  // Two second reads of the 890s, section 122. The good one is a control and the bad one is the
  // reason to cross check: it defeats the anchor, so both codecs have to agree about what the
  // fallback then returns, and a divergence there would be invisible in every other test.
  'h890_config_rescan',
  'h890_config_2_rescan',
  'h890_config_2_redump_1',
  'h890_config_2_redump_2',
  'h890_config_2_redump_3',
  // The two regions Logitech's own client read off the spare Harmony One, section 215. Both are
  // duplicates of containers already in this list, deliberately: the user config's vector must equal
  // `one_spare_before_sync`'s and the embedded one's must equal `one_safemode`'s apart from where the
  // container sits in its file. That is the whole value, since the two copies of each arrived by
  // routes with nothing in common. They are excluded from the corpus wide totals for the same reason
  // they are included here, `PARSEABLE_EXCLUDED` in `packages/lab`, which is not a contradiction: a
  // total is distorted by a duplicate and a comparison is not.
  'vendor_region_user_config',
  'vendor_region_embedded_config',
];

for (const name of CONTAINERS) {
  test(`${name} matches the Python parser field for field`, skipUnlessGolden(name), () => {
    // Parsed exactly as the file sits on disk, no EZHex unwrapping, which is what puts
    // `blob_offset` and every `file_offset` inside the comparison. Confusing a blob offset with a
    // file offset is a mistake that has already cost time on this project.
    const container = parse(load(name) as Uint8Array);
    assert.deepEqual(summary(container), goldenVector(name));
  });
}

/**
 * The checks every golden vector carries, by name. Listed rather than counted, because a count
 * cannot tell a vector that lost `trailer_checksum_recomputes` from one that gained a check nobody
 * asked for, and the count is what stood here as a floor of seven against a real fifteen.
 */
const UNIVERSAL_CHECKS = [
  'end_addr_points_at_end_marker',
  'flash_base_is_block_aligned',
  'format_high_half_is_zero',
  'last_section_is_null',
  'marker_as_expected_for_family',
  'format_states_the_pointer_count',
  'section_spare_bytes_are_zero',
  'section_table_ends_at_the_marker',
  'sections_ascend',
  'sections_within_blob',
  'slot0_is_a_feed_frame',
  'slot1_states_the_architecture',
  'slot3_is_a_timestamp',
  'trailer_checksum_recomputes',
];

test('the vectors carry the fields worth comparing, rather than being nearly empty', () => {
  // Guards the comparison itself. A vector reduced to a couple of scalars, or a summary that
  // quietly stopped emitting sections, would let every test above pass while checking almost
  // nothing.
  const present = CONTAINERS.map(goldenVector).filter((v) => v !== undefined);
  if (present.length === 0) return; // no lab: the skips above have already said so
  let complete = 0;
  for (const vector of present) {
    for (const field of ['flash_base', 'end_addr', 'pointer_count', 'trailer_checksum']) {
      assert.ok(field in vector, `vector is missing ${field}`);
    }
    // The section count is the vector's own `pointer_count` and not a floor of nineteen. That is
    // stronger than any literal here, because it is a closure between two fields the Python side
    // emitted separately: a summary that stopped emitting sections would have to corrupt the count
    // in the same direction to pass, and the four values it takes, 20 to 23, are the four pointer
    // table lengths in the corpus rather than a number this file chose.
    const sections = vector['sections'] as unknown[];
    assert.ok(Array.isArray(sections), 'a vector has no section table');
    assert.equal(sections.length, vector['pointer_count'], 'one section per pointer slot');
    // And the checks by name, not by count. Fourteen are on every vector; `key_table_is_complete`
    // needs a key table, so it is on 37 of the 41 and the four without one are asserted below.
    const checks = Object.keys(vector['checks'] as object);
    for (const name of UNIVERSAL_CHECKS) assert.ok(checks.includes(name), `no ${name} check`);
    assert.ok(checks.every((n) => n === 'key_table_is_complete' || UNIVERSAL_CHECKS.includes(n)),
      `an unexpected check: ${checks.filter((n) => n !== 'key_table_is_complete' && !UNIVERSAL_CHECKS.includes(n)).join(', ')}`);
    if (checks.includes('key_table_is_complete')) complete += 1;
  }
  // 42 since 26 August 2026: the Harmony 895, the first arch 10 container with a known answer,
  // section 178. 41 before it, when the phase 7 pair landed, section 174. 45 since the two regions
  // Logitech's own client read off the spare Harmony One, section 215, which are deliberately
  // duplicates of vectors already here.
  // 46 since `one_spare_20260830`, 30 August 2026, and unlike the pair before it this one is not a
  // duplicate of anything: it is a configuration nothing here had seen.
  // 47 since the read taken after the first write, section 222, which **is** a duplicate of that one
  // and is kept for exactly that: a vector that stopped matching would say the write changed
  // something.
  assert.equal(present.length, 47, 'every vector, which is what `make golden` compares');
  // 38 since the Harmony 895 landed: its key table reads with the existing reader even though
  // every other arch 10 reader is gated, which is what made section 177's keypad closure possible
  // without any arch 10 progress at all.
  // 39 since the Harmony 350, section 194: an arch 16 container's key table reads with the existing
  // reader, the same way the Harmony 895's did, which is a property of the reader and not of a mapping.
  // 41 since section 215's pair, both of which have one: the user config duplicates
  // `one_spare_before_sync` and the embedded one duplicates `one_safemode`.
  // 42 since `one_spare_20260830`, an ordinary arch 12 container read off a Harmony One, and 43 since
  // the read taken after the first write, which duplicates it.
  assert.equal(complete, 43, 'the vectors whose container has a key table at all');

  // **The number sender field, and why it needs its own guard.** It is an empty array on 30 vectors
  // and null on 8, with eight carrying a record since 30 August 2026, and this comment said 25 and 9
  // while the assertions below said 28 and 8, which is
  // prose drifting away from the numbers beside it. A summary that stopped emitting the field would
  // break nothing anybody would notice:
  // every comparison would still pass, and the two vectors where the two implementations are actually
  // compared on a record would go quiet. Same shape as section 148's hollow claim, where a count of
  // what a reader looked for could not see what it never looked at.
  const senders = present.map((v) => v['number_senders'] as unknown[] | null);
  assert.equal(senders.every((one) => one !== undefined), true, 'a vector is missing number_senders');
  // **7 since arch 10 was switched on**, section 184, down from 10. The three that moved are exactly
  // the three arch 10 reads whose trailer checksum recomputes: base slot 16 is aligned now, so those
  // containers answer the question and the answer is an empty array. The five still null are damaged
  // reads of one Harmony 890, section 122, plus the two containers found inside arch 8 firmware
  // images, which report architecture 0 and have no alignment at all.
  // 8 since the Harmony 350, section 194: arch 16 has no slot mapping, so base slot 16 is not
  // readable on it, which is the same gate arch 10 sat behind before section 184.
  assert.equal(senders.filter((one) => one === null).length, 8, 'the containers with no readable slot');
  // 30 since section 215's pair, both of which declare none, like the two vectors they duplicate.
  assert.equal(senders.filter((one) => Array.isArray(one) && one.length === 0).length, 30);
  // **Four since the second compiled sample**, and the reason is the account rather than the request:
  // every configuration compiled from the account that carries favourite channels carries the sender
  // record too, whichever appliances are on it that day. Three of them were made deliberately for base
  // slot 16 and this one came with it, section 165.
  // Seven since the phase 7 pair: both compiles come from the account that carries favourite
  // channels, so both carry the sender record, section 174.
  // **Eight since `one_spare_20260830`, and it is not a made config**, which is why the message
  // below no longer says so: it is a read off the spare Harmony One of whatever Logitech's software
  // last synced onto it, and it carries the record for the same reason the compiles do, the account
  // behind it having favourite channels.
  // Nine since the read taken after the first write, which duplicates the one before it: the record
  // survived the erase and the write, which is the same statement as the whole file comparison and
  // is worth having on this field in particular, base slot 16 being the one the two implementations
  // are compared on at all.
  assert.equal(senders.filter((one) => Array.isArray(one) && one.length > 0).length, 9,
    'the configs that populate base slot 16');
});

test('the list above covers exactly what the Python side writes a vector for', () => {
  // The check that should always have been here. `h525_config_2` sat in `tools/golden.py` and not
  // in this file, so a vector was written and never read, which looks identical to a passing
  // comparison. Parsed out of the tuple rather than imported, since one side is Python.
  const source = readFileSync(join(REPO_ROOT, 'tools', 'golden.py'), 'utf8');
  const block = /^CONTAINERS = \($(.*?)^\)$/ms.exec(source);
  assert.ok(block, 'tools/golden.py has no CONTAINERS tuple in the expected shape');
  const python = [...block[1]!.matchAll(/'([a-z0-9_]+)'/g)].map((m) => m[1] as string);
  assert.equal(python.length, 47, 'the golden vectors, which is what `make golden` prints');
  assert.deepEqual([...CONTAINERS].sort(), python.sort());
});

test('a mutated container does not match its vector', () => {
  // A comparison that cannot fail is not a comparison. Flipping one byte of the format word has
  // to show up, or these tests are asserting that two undefineds are equal.
  const original = load('h700_config');
  const vector = goldenVector('h700_config');
  if (original === undefined || vector === undefined) return;
  const mutated = new Uint8Array(original);
  const formatWord = (parse(original).blobOffset as number) + 8;
  mutated[formatWord + 1] = (mutated[formatWord + 1] as number) ^ 0x01;
  assert.notDeepEqual(summary(parse(mutated)), vector);
});
