/**
 * The port, held against what the Python parser says about the same bytes.
 *
 * This is the test that makes the port provable rather than plausible. The other test files state
 * the same claims twice, once per language, and two statements written from one understanding can
 * be wrong in the same way. A vector generated by one implementation and asserted by the other
 * cannot be: every field of it is a number the other side has to reproduce, including the ones
 * nobody thought to write a test about.
 *
 * Generate or refresh with `tools/golden.py --write`. The vectors live in the lab directory
 * because they describe private dumps, so these tests skip cleanly on a bare checkout, like every
 * other image-backed test here.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';

import { goldenVector, load, skipUnlessGolden } from '@harmony/lab';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parse, summary } from '../src/index.ts';

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..', '..');

/**
 * Same list as `CONTAINERS` in `tools/golden.py`, including the samples that are not somebody's
 * configuration. An implementation can agree on the ordinary cases and diverge on the degenerate
 * ones: the empty 0xFEED frame only occurs in a safe mode config.
 *
 * The list is written out rather than derived, because a test should say what it covers. **But the
 * comment that used to stand here, saying duplication is what stops a sample being lost, was
 * exactly wrong**: `h525_config_2` had been on the Python side and not on this one, so its
 * comparison had never run and nothing said so. The last test in this file compares the two lists
 * now, so the duplication is checked instead of trusted.
 */
const CONTAINERS = [
  'one_safemode',
  'one34_region2',
  'h700_gspm',
  'h600_safemode_gspm',
  'h650_safemode_gspm',
  'one_config',
  'one_config_unprogrammed',
  'h600_config',
  'h700_config',
  'h700_config_2',
  'h525_config',
  'h525_config_2',
  'arch8_config_a',
  'arch8_config_b',
  'arch8_config_c',
  'arch8_config_d',
  'h525_safemode_ahcm',
  // The same container in situ, at blob offset 0x8000 of the 64 KiB external firmware region it was
  // cut out of. A deliberate duplicate: it is what checks the cut was made in the right place, since
  // both parses have to agree about the base, the end address and every check. Section 118.
  'h525_external_firmware',
  'one_spare_before_sync',
  'one_spare_after_sync',
  // The third state of that unit, section 155, and the richest known answer sample: a real five
  // device setup built by MyHarmony from an account whose contents we can ask for.
  'one_spare_myharmony',
  // The two configs Logitech compiled to a specification we wrote, section 132: the only samples
  // whose devices and activities were chosen before the bytes existed, so a disagreement between the
  // two implementations about them would be a disagreement about a known answer.
  'calibration_one',
  'calibration_h600',
  // The first config anywhere to populate base slot 16, so the only vector where the two
  // implementations of that reader are compared on a record rather than on an empty list.
  'calibration_favchannels',
  // The second to populate it, and the one that shows the section does not carry every favourite:
  // two of its five spell the number out one digit code at a time. Section 156.
  'calibration_favzero',
  // The largest sample anywhere here, section 165: fifteen appliances chosen so that every protocol
  // family in Logitech's catalogue the corpus could not settle appears in it. This is the first and
  // largest of the three compiled samples the rhythm table's thirty non corpus entries are measured
  // off, so a disagreement about it is a disagreement about the table. The count used to be given as
  // eighteen off this file alone, which was true when it was the only one.
  'compiled_protocols',
  // The second of the pair, ten more appliances chosen for the families the first did not reach.
  'compiled_protocols_2',
  // The third, an hour later: the four the second had no room for, plus the appliance whose account
  // name the rebuilt capture of the first could not recover, which is what put one entry back to
  // being confirmed by two routes.
  'compiled_protocols_3',
  // The arch 8 safe mode container, found inside the firmware image itself at blob offset 0xE000
  // rather than in a file of its own. Section 114.
  'arch8_code_880',
  'arch8_code_885',
  // An 885 user config, and the first arch 10 container, whose four failing checks the vector
  // records rather than hides. Sections 113 and 115.
  'arch8_config_880',
  'arch8_config_885',
  'h890_config',
  'h890_config_2',
  // Two second reads of the 890s, section 122. The good one is a control and the bad one is the
  // reason to cross check: it defeats the anchor, so both codecs have to agree about what the
  // fallback then returns, and a divergence there would be invisible in every other test.
  'h890_config_rescan',
  'h890_config_2_rescan',
  'h890_config_2_redump_1',
  'h890_config_2_redump_2',
  'h890_config_2_redump_3',
];

for (const name of CONTAINERS) {
  test(`${name} matches the Python parser field for field`, skipUnlessGolden(name), () => {
    // Parsed exactly as the file sits on disk, no EZHex unwrapping, which is what puts
    // `blob_offset` and every `file_offset` inside the comparison. Confusing a blob offset with a
    // file offset is a mistake that has already cost time on this project.
    const container = parse(load(name) as Uint8Array);
    assert.deepEqual(summary(container), goldenVector(name));
  });
}

/**
 * The checks every golden vector carries, by name. Listed rather than counted, because a count
 * cannot tell a vector that lost `trailer_checksum_recomputes` from one that gained a check nobody
 * asked for, and the count is what stood here as a floor of seven against a real fifteen.
 */
const UNIVERSAL_CHECKS = [
  'end_addr_points_at_end_marker',
  'flash_base_is_block_aligned',
  'format_high_half_is_zero',
  'last_section_is_null',
  'marker_as_expected_for_family',
  'pointer_count_known',
  'section_spare_bytes_are_zero',
  'section_table_ends_at_the_marker',
  'sections_ascend',
  'sections_within_blob',
  'slot0_is_a_feed_frame',
  'slot1_states_the_architecture',
  'slot3_is_a_timestamp',
  'trailer_checksum_recomputes',
];

test('the vectors carry the fields worth comparing, rather than being nearly empty', () => {
  // Guards the comparison itself. A vector reduced to a couple of scalars, or a summary that
  // quietly stopped emitting sections, would let every test above pass while checking almost
  // nothing.
  const present = CONTAINERS.map(goldenVector).filter((v) => v !== undefined);
  if (present.length === 0) return; // no lab: the skips above have already said so
  let complete = 0;
  for (const vector of present) {
    for (const field of ['flash_base', 'end_addr', 'pointer_count', 'trailer_checksum']) {
      assert.ok(field in vector, `vector is missing ${field}`);
    }
    // The section count is the vector's own `pointer_count` and not a floor of nineteen. That is
    // stronger than any literal here, because it is a closure between two fields the Python side
    // emitted separately: a summary that stopped emitting sections would have to corrupt the count
    // in the same direction to pass, and the four values it takes, 20 to 23, are the four pointer
    // table lengths in the corpus rather than a number this file chose.
    const sections = vector['sections'] as unknown[];
    assert.ok(Array.isArray(sections), 'a vector has no section table');
    assert.equal(sections.length, vector['pointer_count'], 'one section per pointer slot');
    // And the checks by name, not by count. Fourteen are on every vector; `key_table_is_complete`
    // needs a key table, so it is on 35 of the 39 and the four without one are asserted below.
    const checks = Object.keys(vector['checks'] as object);
    for (const name of UNIVERSAL_CHECKS) assert.ok(checks.includes(name), `no ${name} check`);
    assert.ok(checks.every((n) => n === 'key_table_is_complete' || UNIVERSAL_CHECKS.includes(n)),
      `an unexpected check: ${checks.filter((n) => n !== 'key_table_is_complete' && !UNIVERSAL_CHECKS.includes(n)).join(', ')}`);
    if (checks.includes('key_table_is_complete')) complete += 1;
  }
  assert.equal(present.length, 39, 'every vector, which is what `make golden` compares');
  assert.equal(complete, 35, 'the vectors whose container has a key table at all');

  // **The number sender field, and why it needs its own guard.** It is an empty array on 25 vectors
  // and null on 9, so a summary that stopped emitting it would break nothing anybody would notice:
  // every comparison would still pass, and the two vectors where the two implementations are actually
  // compared on a record would go quiet. Same shape as section 148's hollow claim, where a count of
  // what a reader looked for could not see what it never looked at.
  const senders = present.map((v) => v['number_senders'] as unknown[] | null);
  assert.equal(senders.every((one) => one !== undefined), true, 'a vector is missing number_senders');
  assert.equal(senders.filter((one) => one === null).length, 9, 'the containers with no readable slot');
  assert.equal(senders.filter((one) => Array.isArray(one) && one.length === 0).length, 25);
  // **Four since the second compiled sample**, and the reason is the account rather than the request:
  // every configuration compiled from the account that carries favourite channels carries the sender
  // record too, whichever appliances are on it that day. Three of them were made deliberately for base
  // slot 16 and this one came with it, section 165.
  assert.equal(senders.filter((one) => Array.isArray(one) && one.length > 0).length, 5,
    'the made configs that populate base slot 16');
});

test('the list above covers exactly what the Python side writes a vector for', () => {
  // The check that should always have been here. `h525_config_2` sat in `tools/golden.py` and not
  // in this file, so a vector was written and never read, which looks identical to a passing
  // comparison. Parsed out of the tuple rather than imported, since one side is Python.
  const source = readFileSync(join(REPO_ROOT, 'tools', 'golden.py'), 'utf8');
  const block = /^CONTAINERS = \($(.*?)^\)$/ms.exec(source);
  assert.ok(block, 'tools/golden.py has no CONTAINERS tuple in the expected shape');
  const python = [...block[1]!.matchAll(/'([a-z0-9_]+)'/g)].map((m) => m[1] as string);
  assert.equal(python.length, 39, 'the golden vectors, which is what `make golden` prints');
  assert.deepEqual([...CONTAINERS].sort(), python.sort());
});

test('a mutated container does not match its vector', () => {
  // A comparison that cannot fail is not a comparison. Flipping one byte of the format word has
  // to show up, or these tests are asserting that two undefineds are equal.
  const original = load('h700_config');
  const vector = goldenVector('h700_config');
  if (original === undefined || vector === undefined) return;
  const mutated = new Uint8Array(original);
  const formatWord = (parse(original).blobOffset as number) + 8;
  mutated[formatWord + 1] = (mutated[formatWord + 1] as number) ^ 0x01;
  assert.notDeepEqual(summary(parse(mutated)), vector);
});
