/**
 * The port, held against what the Python parser says about the same bytes.
 *
 * This is the test that makes the port provable rather than plausible. The other test files state
 * the same claims twice, once per language, and two statements written from one understanding can
 * be wrong in the same way. A vector generated by one implementation and asserted by the other
 * cannot be: every field of it is a number the other side has to reproduce, including the ones
 * nobody thought to write a test about.
 *
 * Generate or refresh with `tools/golden.py --write`. The vectors live in the lab directory
 * because they describe private dumps, so these tests skip cleanly on a bare checkout, like every
 * other image-backed test here.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';

import { goldenVector, load, skipUnlessGolden } from '@harmony/lab';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parse, summary } from '../src/index.ts';

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..', '..');

/**
 * Same list as `CONTAINERS` in `tools/golden.py`, including the samples that are not somebody's
 * configuration. An implementation can agree on the ordinary cases and diverge on the degenerate
 * ones: the empty 0xFEED frame only occurs in a safe mode config.
 *
 * The list is written out rather than derived, because a test should say what it covers. **But the
 * comment that used to stand here, saying duplication is what stops a sample being lost, was
 * exactly wrong**: `h525_config_2` had been on the Python side and not on this one, so its
 * comparison had never run and nothing said so. The last test in this file compares the two lists
 * now, so the duplication is checked instead of trusted.
 */
const CONTAINERS = [
  'one_safemode',
  'one34_region2',
  'h700_gspm',
  'h600_safemode_gspm',
  'h650_safemode_gspm',
  'one_config',
  'one_config_unprogrammed',
  'h600_config',
  'h700_config',
  'h700_config_2',
  'h525_config',
  'h525_config_2',
  'arch8_config_a',
  'arch8_config_b',
  'arch8_config_c',
  'arch8_config_d',
  'h525_safemode_ahcm',
  // The same container in situ, at blob offset 0x8000 of the 64 KiB external firmware region it was
  // cut out of. A deliberate duplicate: it is what checks the cut was made in the right place, since
  // both parses have to agree about the base, the end address and every check. Section 118.
  'h525_external_firmware',
  'one_spare_before_sync',
  'one_spare_after_sync',
  // The arch 8 safe mode container, found inside the firmware image itself at blob offset 0xE000
  // rather than in a file of its own. Section 114.
  'arch8_code_880',
  'arch8_code_885',
  // An 885 user config, and the first arch 10 container, whose four failing checks the vector
  // records rather than hides. Sections 113 and 115.
  'arch8_config_885',
  'h890_config',
  'h890_config_2',
];

for (const name of CONTAINERS) {
  test(`${name} matches the Python parser field for field`, skipUnlessGolden(name), () => {
    // Parsed exactly as the file sits on disk, no EZHex unwrapping, which is what puts
    // `blob_offset` and every `file_offset` inside the comparison. Confusing a blob offset with a
    // file offset is a mistake that has already cost time on this project.
    const container = parse(load(name) as Uint8Array);
    assert.deepEqual(summary(container), goldenVector(name));
  });
}

test('the vectors carry the fields worth comparing, rather than being nearly empty', () => {
  // Guards the comparison itself. A vector reduced to a couple of scalars, or a summary that
  // quietly stopped emitting sections, would let every test above pass while checking almost
  // nothing.
  const present = CONTAINERS.map(goldenVector).filter((v) => v !== undefined);
  if (present.length === 0) return; // no lab: the skips above have already said so
  for (const vector of present) {
    for (const field of ['flash_base', 'end_addr', 'pointer_count', 'trailer_checksum']) {
      assert.ok(field in vector, `vector is missing ${field}`);
    }
    const sections = vector['sections'] as unknown[];
    assert.ok(Array.isArray(sections) && sections.length >= 19, 'a vector has no section table');
    assert.ok(Object.keys(vector['checks'] as object).length >= 7, 'a vector has no checks');
  }
});

test('the list above covers exactly what the Python side writes a vector for', () => {
  // The check that should always have been here. `h525_config_2` sat in `tools/golden.py` and not
  // in this file, so a vector was written and never read, which looks identical to a passing
  // comparison. Parsed out of the tuple rather than imported, since one side is Python.
  const source = readFileSync(join(REPO_ROOT, 'tools', 'golden.py'), 'utf8');
  const block = /^CONTAINERS = \($(.*?)^\)$/ms.exec(source);
  assert.ok(block, 'tools/golden.py has no CONTAINERS tuple in the expected shape');
  const python = [...block[1]!.matchAll(/'([a-z0-9_]+)'/g)].map((m) => m[1] as string);
  assert.ok(python.length >= 19, 'the tuple was read as empty, so this test proves nothing');
  assert.deepEqual([...CONTAINERS].sort(), python.sort());
});

test('a mutated container does not match its vector', () => {
  // A comparison that cannot fail is not a comparison. Flipping one byte of the format word has
  // to show up, or these tests are asserting that two undefineds are equal.
  const original = load('h700_config');
  const vector = goldenVector('h700_config');
  if (original === undefined || vector === undefined) return;
  const mutated = new Uint8Array(original);
  const formatWord = (parse(original).blobOffset as number) + 8;
  mutated[formatWord + 1] = (mutated[formatWord + 1] as number) ^ 0x01;
  assert.notDeepEqual(summary(parse(mutated)), vector);
});
