/**
 * Mode 0's key list generated from its rule, against every Harmony 600, 650 and 700 sample section 311
 * named, plus the two Harmony 650 compiles of section 306. Section 311 and section 315.
 *
 * Byte equality with the bytes after the end marker is the whole claim: the population, the one
 * instruction that is not a swallow, the 700's leading entry and the order all have to be right for it
 * to pass, and the order is the part a copy would hide.
 */
import test from 'node:test';
import assert from 'node:assert/strict';

import { require_, skipUnless } from '@harmony/lab';
import {
  keyListBucket,
  keyListCapacity,
  keyListHash,
  keyListOrder,
  modeZeroEntries,
  modeZeroKeyList,
  parse,
} from '../src/index.ts';

/** Section 311's four plus the two Harmony 650 compiles no remote held, section 306. */
const SIX_FIFTY = ['h600_config', 'calibration_h600', 'h650_config_region', 'h650_panasonic_config',
  'h650_power_hold_compile', 'h650_power_hold_compile_2'] as const;

/** The variable each Harmony 700 sample's leading entry sets, as `tests/test_gspm.py` pins them. */
const SEVEN_HUNDRED = { h700_config: 40, h700_config_2: 40, h700_28_config_region: 44, h700_power_hold_compile: 43 } as const;

/** The bytes after the end marker, as long as the generated list, which is where a writer puts it. */
function storedList(name: string, length: number): Uint8Array {
  const c = parse(require_(name));
  assert.equal(c.family.keyTableAtMarker, true, name);
  // The marker is four bytes, `LWJL` on arch 14, and the list follows it directly.
  const at = c.markerOffset + 4;
  return c.blob.subarray(at, at + length);
}

test('the Harmony 600 and 650 mode 0 list is generated byte for byte', skipUnless(...SIX_FIFTY), () => {
  const generated = modeZeroKeyList('harmony-650');
  assert.equal(generated.length, 1 + 4 * 162);
  assert.deepEqual(modeZeroKeyList('harmony-600'), generated, 'one list for both models');
  for (const name of SIX_FIFTY) {
    assert.deepEqual(storedList(name, generated.length), generated, name);
  }
});

test('the Harmony 700 mode 0 list is generated byte for byte, given its variable',
     skipUnless(...Object.keys(SEVEN_HUNDRED)), () => {
  for (const [name, variable] of Object.entries(SEVEN_HUNDRED)) {
    const generated = modeZeroKeyList('harmony-700', { variable });
    assert.equal(generated.length, 1 + 4 * 163);
    assert.deepEqual(storedList(name, generated.length), generated, name);
  }
});

test('the order is what the test checks, and a plain tag order fails it', skipUnless('h650_config_region'), () => {
  // The control: the same entries sorted by tag, which is what a generator that did not know the
  // rule would most likely write. It has to differ from the stored bytes, or the byte equality above
  // would be saying nothing about the order.
  const entries = modeZeroEntries('harmony-650');
  const byTag = [...entries].sort((a, b) => a.tag - b.tag);
  const bytes = new Uint8Array(1 + 4 * byTag.length);
  bytes[0] = byTag.length;
  byTag.forEach((one, k) => bytes.set([one.tag, one.operand & 0xff, one.operand >>> 8, one.opcode], 1 + 4 * k));
  assert.notDeepEqual(storedList('h650_config_region', bytes.length), bytes);
  // A sharper control than tag order: the same entries ordered by either reduced form of the hash, which
  // differ from the real one only in one term. Both have to fail too, or the bytes would not be
  // pinning the hash.
  for (const reduced of [(t: number) => t ^ (t >>> 4), (t: number) => t ^ (t >>> 7)]) {
    const ordered = [...entries].sort((a, b) => reduced(a.tag) - reduced(b.tag));
    const other = new Uint8Array(1 + 4 * ordered.length);
    other[0] = ordered.length;
    ordered.forEach((one, k) => other.set([one.tag, one.operand & 0xff, one.operand >>> 8, one.opcode], 1 + 4 * k));
    assert.notDeepEqual(storedList('h650_config_region', other.length), other);
  }
  // And the one swallow that is not one, by position: the press of scan 25 is entry 70 of 162.
  assert.deepEqual(entries.findIndex((one) => one.opcode !== 0), 70);
  assert.deepEqual(entries[70], { tag: 0x80 | 25, operand: 0xfffc, opcode: 0x07 });
});

test('the hash, the capacity and the refusal of a shared bucket', () => {
  // Java 6 and 7's supplemental hash for a value under 4096, written out on three tags.
  assert.equal(keyListHash(0x44), 0x44 ^ 0x04 ^ 0x00);
  assert.equal(keyListHash(0x89), 0x89 ^ 0x08 ^ 0x01);
  assert.equal(keyListHash(0xff), 0xff ^ 0x0f ^ 0x01);
  // At 256 buckets it is a bijection on a byte, which is why the 600's list has no ties.
  assert.equal(new Set(Array.from({ length: 256 }, (_, t) => keyListHash(t))).size, 256);
  // 16 to start, doubling past three quarters full: 12 fits 16, 13 does not, 162 and 163 fit 256.
  assert.deepEqual([1, 12, 13, 24, 25, 48, 49, 96, 97, 162, 163, 192, 193].map(keyListCapacity),
                   [16, 16, 32, 32, 64, 64, 128, 128, 256, 256, 256, 256, 512]);
  assert.equal(keyListBucket(0x06, 163), 6);
  // Two tags in one bucket of sixteen, 0x06 and 0x8f, the Harmony One's tie: refused, not guessed.
  assert.equal(keyListBucket(0x06, 2), keyListBucket(0x8f, 2));
  assert.throws(() => keyListOrder([0x06, 0x8f]), /share bucket 6/);
  assert.throws(() => keyListOrder([0x100]), /not a byte/);
  // The variable is the 700's alone.
  assert.throws(() => modeZeroKeyList('harmony-650', { variable: 40 }), /takes no variable/);
  assert.throws(() => modeZeroKeyList('harmony-700'), /sets one state variable/);
  assert.throws(() => modeZeroKeyList('harmony-700', { variable: 128 }), /sets one state variable/);
});
