/**
 * What rhythm each protocol family uses, so a code stated as a name and a number can be emitted.
 *
 * **Generated by `packages/codec/bin/protocols.ts --write`, do not edit by hand.** `make protocols`
 * prints the measurement and `--write` puts it here, the same arrangement as the glyph table.
 *
 * **Why this file has to exist.** Logitech's device database gives a protocol name and a number and never
 * the rhythm: the raw field was null on all 419 commands ever fetched. So a device taken from their
 * catalogue cannot be written to a remote without knowing what "Sony 12 Bit" sounds like. Section 152
 * measured that the durations can be copied off any other code of the same **appliance**, which serves a
 * config that already drives it and cannot serve a document starting from nothing.
 *
 * **An entry is a family at a carrier frequency**, because a rhythm is only a rhythm at a frequency and
 * that is how a family is looked up in Logitech's catalogue. It is **not** because a family arrives at
 * two of them: that reading came from two entries their analyser both called SharpO1 48 Bit, which are
 * `Sharp 48 Bit 2` at 38 kHz and `PanasonicV2 48 Bit` at 36.4 kHz, and Logitech states one carrier
 * per family.
 *
 * **`framePeriod` replaces the closing space rather than tabling it.** On a pulse width protocol the
 * space that closes the last pair pads the frame out to a constant total, so it is shorter by one bit's
 * worth for every one bit the code carries. Tabling it made Sony 12 Bit look like three protocols over
 * three codes; computing it from the period makes it one. Both Sony families come out at exactly 45000
 * microseconds, which is the published frame period of that protocol and was not fitted to.
 *
 * **A family is named by Logitech's catalogue, and their analyser's name is kept beside it as
 * `heardAs`.** This said the table held both names for one rhythm because there was no rule for which a
 * caller would ask with. There is a rule: the catalogue **states** the rhythm, so the rhythm identifies
 * the family, and `nameByCatalogue` does that lookup. It moved four groups, of which their analyser had
 * named three outright wrongly, and the fourth apart from a family it had merged into. Their two
 * vocabularies still differ, section 159, which is what `heardAs` is for.
 *
 * **`exact` and `spread` are what the entry is worth, and they are two different claims.** `exact` is
 * how many of its codes this rhythm reproduces to the microsecond, which is what Logitech's own compiler
 * emitted. `spread` is the tightest band that covers all of them, which is what an appliance's receiver
 * cares about. An entry with a spread of 0.02 will be accepted by the equipment and will not be byte
 * identical to a config Logitech built.
 */
import type { FrameCarrier } from './irframe.ts';

export interface StatedProtocol {
  /** Logitech's own name for it, as their analyser and their catalogue spell it. */
  readonly family: string;
  /** The carrier as a record states it, a period in nanoseconds. 38 kHz is 26315. */
  readonly periodNs: number;
  /**
   * `[0, 0]` where the protocol has no lead in and opens on its first bit cell.
   *
   * **Absent, with `flat`, `zero`, `one` and `carries`, on a biphase family**, which has none of
   * them: see `biphase` below. A row has one shape or the other and never both, and
   * `test/stated.test.ts` asserts that.
   */
  readonly header?: readonly [number, number];
  readonly flat?: number;
  /**
   * The opening burst, where the protocol makes it longer than the rest.
   *
   * Only the Sharp family here does, 270 against 260 on every record of it, and it matters because
   * without it a rebuilt code differs from what their compiler emits on its very first pulse.
   */
  readonly firstMark?: number;
  /**
   * The mark of a **set** cell, on the three families whose mark rides with its own cell's bit,
   * section 170. `flat` is then the clear cell's mark. Absent everywhere the flat half really is
   * one length.
   */
  readonly oneMark?: number;
  readonly zero?: number;
  readonly one?: number;
  readonly carries?: FrameCarrier;
  /** The constant total a pulse width frame is padded out to, absent on a pulse distance one. */
  readonly framePeriod?: number;
  /**
   * The whole first block past the frame, section 171: the frame in its copies (`full` with the
   * lead in, `bare` without), literal words (signed microseconds, positive a mark), and pad
   * spaces sharing one per record value plus the stated extra, solved from `total`. Absent where
   * the family's records do not agree on one shape, and `blockOfStatedCode` refuses such a
   * family rather than guessing, because a tail can hold a second command, section 152.
   */
  readonly tail?: {
    readonly items: readonly ({ readonly copy: 'full' | 'bare'; readonly at?: number }
      | { readonly words: readonly number[] }
      | { readonly pad: number })[];
    readonly total?: number;
    readonly copyPeriod?: number;
  };
  /** How many of the family's records rebuild their whole first block from this entry. */
  readonly tailExact?: number;
  /**
   * The held block, the record's second pointer: what repeats for as long as the key is down, and
   * whose duration is the repeat rate the user feels, section 127. Same shape as `tail`. Whether
   * a record carries one at all is the command's own property, so `heldOf` states the population
   * this was measured over, and Toshiba's is its ditto frame alone with no copy in it.
   */
  readonly held?: {
    readonly items: readonly ({ readonly copy: 'full' | 'bare'; readonly at?: number }
      | { readonly words: readonly number[] }
      | { readonly pad: number })[];
    readonly total?: number;
    readonly copyPeriod?: number;
  };
  readonly heldExact?: number;
  readonly heldOf?: number;
  /**
   * A biphase family, where the bit is in **which half** of one cell the carrier is on.
   *
   * Section 162. There is no lead in pair, no constant half and no two carried lengths, so none of the
   * fields above apply: what there is instead is one half cell, a fixed prelude the family always sends,
   * and which half of the cell means a set bit. Four families here are of this kind and each reproduces
   * every one of its records byte for byte.
   */
  readonly biphase?: {
    /** One half cell of carrier. */
    readonly mark: number;
    /** One half cell of silence. */
    readonly space: number;
    /** A different opening mark where the family sends one. */
    readonly firstMark?: number;
    /** Everything before the first bit cell, exactly as a record stores it. */
    readonly lead: readonly { readonly mark: boolean; readonly us: number }[];
    /** Whether a mark in the **first** half of a cell means a set bit. RC-6 is the other way up. */
    readonly setIsMark: boolean;
  };
  /**
   * The frame is one value sent in sections of these widths, section 166.
   *
   * `Samsung 38 Bit` is the family that needed it: the catalogue states two values per code and one
   * width, and the wire is one header, the first section's cells, a structural space carrying that
   * section's final set bit, the second section's cells, and a closing silence carrying the last bit of
   * all. The widths sum to the width the family's name states, which is the closure that settled what
   * "38 Bit" means: across the pair.
   */
  readonly sections?: readonly number[];
  /** The space carrying a non final section's last set bit. Present exactly when `sections` is. */
  readonly sectionSpace?: number;
  /** The closing silence, which on a sectioned family carries the final bit and is a measured constant. */
  readonly closing?: number;
  /**
   * The long toggle shape, set instead of the frame and biphase fields, section 168, one family.
   *
   * A code states three values, and the wire is a leader, head cells per kind, one double width toggle
   * cell stored merged, data cells per position, and the whole frame `copies` times with the stored
   * `gap` words after each. A set bit is the cell whose first half is silence, in all three regions.
   * `pulsesOfLongToggle` in `irframe.ts` is the emitter and reproduces every record of the
   * family word for word, copies and gaps included.
   */
  readonly longToggle?: {
    readonly leader: readonly [number, number];
    readonly head: { readonly mark: number; readonly space: number; readonly bits: number };
    readonly toggle: number;
    readonly data: { readonly first: number; readonly second: number; readonly bits: number };
    readonly gap: readonly number[];
    readonly copies: number;
  };
  /**
   * The quaternary shape, set instead of the frame and biphase fields, section 169, one family.
   *
   * `Quad` in the family's name is the base of its digits twice over: the catalogue writes the
   * values in base 4 and the wire sends one digit per cell as one of four space lengths, two bits at a
   * time, each cell closed by the constant `mark`. A constant start digit of 0 precedes the values,
   * `digits` says how many quaternary digits each stated value takes, and the stored `gap` words
   * close the record. `pulsesOfQuad` in `irframe.ts` is the emitter and reproduces every record
   * word for word, gap included.
   */
  readonly quad?: {
    readonly firstMark: number;
    readonly mark: number;
    readonly spaces: readonly [number, number, number, number];
    readonly digits: readonly number[];
    readonly gap: readonly number[];
  };
  /** How many corpus codes the entry was measured over, and how many it reproduces exactly. */
  readonly codes: number;
  readonly exact: number;
  /** The tightest band, as a fraction, that covers every code of the entry. */
  readonly spread: number;
  /**
   * Where the durations came from, which decides what the entry is worth.
   *
   * `corpus` is measured off records a configuration already holds, so it reproduces what Logitech's
   * own compiler emitted and `exact` says how often. `documented` is the published nominal timing of
   * that protocol, taken from third party protocol documentation, for a family **no configuration here
   * holds a single record of**: the corpus cannot supply it and no amount of reading it will.
   *
   * A documented entry has `codes: 0` because it was measured over none, which is the honest number
   * and not a placeholder. What it has instead is `readBack`.
   */
  readonly source: 'corpus' | 'compiled' | 'both' | 'documented';
  /**
   * Catalogue codes emitted with this rhythm that Logitech's own analyser decoded back to the exact
   * number they were built from.
   *
   * **This is the only evidence a documented entry has, and it is weaker than `exact` in a way worth
   * stating.** `exact` says the durations are the ones their compiler emitted. This says their own
   * decoder, hearing our train, recovers the bits: the marks and spaces land in the bands it sorts into
   * zeros and ones. That is what an appliance's receiver does too, so it is the right kind of evidence,
   * and it is still not an appliance and still not byte equality.
   */
  readonly readBack?: number;
  /**
   * What their analyser calls this rhythm, where that is not what their catalogue calls it.
   *
   * **Their analyser's family list is coarser than their catalogue's**, which is measured: emitting a
   * `Pioneer 32 Bit 2` code with Pioneer's durations comes back named `Pioneer 32 Bit`, and their two
   * Sharp families both come back `Proceed 14 Bit`. So a name that does not match is not a wrong
   * rhythm, and name agreement is sufficient evidence rather than necessary.
   */
  readonly heardAs?: string;
}

export const PROTOCOLS: readonly StatedProtocol[] = [
  { family: 'Toshiba 32 Bit', periodNs: 26315, header: [8990, 4490], flat: 568, zero: 552, one: 1662, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [568] }, { pad: 0 }, { words: [8990, -2230, 568, -96078] }], total: 215736 }, tailExact: 703, held: { items: [{ words: [8990, -2230, 568, -96078] }] }, heldExact: 545, heldOf: 545, codes: 703, exact: 703, spread: 0, source: 'both', heardAs: 'MemorexO1 32 Bit' },
  { family: 'Sharp 48 Bit 2', periodNs: 26315, header: [3364, 1682], flat: 408, zero: 431, one: 1272, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [408, -73611] }, { copy: 'full' }, { words: [408, -73611] }, { copy: 'full' }, { words: [408, -73612] }] }, tailExact: 378, held: { items: [{ copy: 'full' }, { words: [408, -73612] }] }, heldExact: 317, heldOf: 317, codes: 378, exact: 378, spread: 0, source: 'both', heardAs: 'SharpO1 48 Bit' },
  { family: 'Sharp 15 Bit 2', periodNs: 27027, header: [0, 0], flat: 260, firstMark: 270, zero: 790, one: 1850, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [260] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [260] }, { pad: 0 }, { copy: 'full' }, { words: [260] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [260] }, { pad: 0 }, { copy: 'full' }, { words: [260] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [260] }, { pad: 1 }], copyPeriod: 67792 }, tailExact: 184, held: { items: [{ copy: 'full' }, { words: [260] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [260] }, { pad: 1 }], copyPeriod: 67792 }, heldExact: 179, heldOf: 209, codes: 220, exact: 220, spread: 0, source: 'compiled' },
  { family: 'Logitech 24 Bit', periodNs: 26315, header: [4000, 4500], flat: 400, zero: 1000, one: 500, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [400, -50001] }] }, tailExact: 206, held: { items: [{ copy: 'full' }, { words: [400, -50001] }] }, heldExact: 171, heldOf: 171, codes: 217, exact: 217, spread: 0, source: 'both' },
  { family: 'Microsoft 30 Bit', periodNs: 27624, biphase: { mark: 441, space: 446, lead: [{ mark: true, us: 2632 }, { mark: false, us: 900 }, { mark: true, us: 441 }, { mark: false, us: 443 }, { mark: true, us: 441 }, { mark: false, us: 439 }, { mark: true, us: 441 }, { mark: false, us: 887 }, { mark: true, us: 441 }, { mark: false, us: 879 }, { mark: true, us: 1323 }, { mark: false, us: 889 }, { mark: true, us: 441 }], setIsMark: false }, tail: { items: [{ copy: 'full' }, { words: [-32767, -17938, -17938] }, { copy: 'full' }, { words: [-32767, -17938, -17938] }, { copy: 'full' }, { words: [-32767, -17938, -17938, -1, 0] }] }, tailExact: 65, held: { items: [{ copy: 'full' }, { words: [-32767, -17938, -17938, -1, 0] }] }, heldExact: 150, heldOf: 150, codes: 213, exact: 213, spread: 0, source: 'both' },
  { family: 'Kreatel IP 22 Bit', periodNs: 17761, biphase: { mark: 325, space: 320, lead: [{ mark: true, us: 320 }, { mark: false, us: 320 }], setIsMark: true }, codes: 164, exact: 164, spread: 0, source: 'both' },
  { family: 'JVC 16 Bit', periodNs: 26315, header: [8400, 4200], flat: 500, zero: 500, one: 1600, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [500] }, { pad: 0 }, { copy: 'bare' }, { words: [500] }, { pad: 0 }, { copy: 'bare' }, { words: [500] }, { pad: 1 }], total: 147601 }, tailExact: 108, held: { items: [{ copy: 'bare' }, { words: [500] }, { pad: 0 }], total: 45001 }, heldExact: 107, heldOf: 107, codes: 108, exact: 108, spread: 0, source: 'compiled' },
  { family: 'Magnavox 13 Bit', periodNs: 26315, biphase: { mark: 880, space: 900, lead: [{ mark: true, us: 880 }], setIsMark: true }, tail: { items: [{ copy: 'full' }, { words: [-32767, -32767, -26466] }, { copy: 'full' }, { words: [-32767, -32767, -26466] }, { copy: 'full' }, { words: [-32767, -32767, -26466, -1, 0] }] }, tailExact: 105, held: { items: [{ copy: 'full' }, { words: [-32767, -32767, -26466, -1, 0] }] }, heldExact: 92, heldOf: 92, codes: 105, exact: 105, spread: 0, source: 'compiled' },
  { family: 'Sharp 15 Bit', periodNs: 27777, header: [0, 0], flat: 250, zero: 800, one: 1800, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [250] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [250] }, { pad: 0 }, { copy: 'full' }, { words: [250] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [250] }, { pad: 0 }, { copy: 'full' }, { words: [250] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [250] }, { pad: 1 }], copyPeriod: 65000 }, tailExact: 95, held: { items: [{ copy: 'full' }, { words: [250] }, { pad: 0 }, { copy: 'full', at: 1 }, { words: [250] }, { pad: 1 }], copyPeriod: 65000 }, heldExact: 93, heldOf: 93, codes: 95, exact: 95, spread: 0, source: 'compiled' },
  { family: 'Sony 12 Bit', periodNs: 25000, header: [2400, 600], flat: 600, zero: 600, one: 1200, carries: 'mark', framePeriod: 45000, tail: { items: [{ copy: 'full' }, { pad: 0 }, { copy: 'full' }, { pad: 0 }, { copy: 'full' }, { pad: 1 }], total: 135001 }, tailExact: 59, held: { items: [{ copy: 'full' }, { pad: 0 }], total: 45001 }, heldExact: 56, heldOf: 56, codes: 59, exact: 59, spread: 0, source: 'both' },
  { family: 'Thomson 12 Bit Toggle', periodNs: 29411, header: [0, 0], flat: 470, zero: 2040, one: 4570, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [470] }, { pad: 0 }, { copy: 'full' }, { words: [470] }, { pad: 0 }, { copy: 'full' }, { words: [470] }, { pad: 1 }], total: 240001 }, tailExact: 59, held: { items: [{ copy: 'full' }, { words: [470] }, { pad: 0 }], total: 80001 }, heldExact: 48, heldOf: 48, codes: 59, exact: 59, spread: 0, source: 'compiled' },
  { family: 'RCAV1 LF 24 Bit', periodNs: 26178, header: [3970, 3980], flat: 490, zero: 2010, one: 1010, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [490, -8460] }, { copy: 'full' }, { words: [490, -8460] }, { copy: 'full' }, { words: [490, -8461] }] }, tailExact: 52, held: { items: [{ copy: 'full' }, { words: [490, -8461] }] }, heldExact: 41, heldOf: 41, codes: 52, exact: 52, spread: 0, source: 'compiled' },
  { family: 'Philips RC5 13 Bit Toggle', periodNs: 27777, biphase: { mark: 889, space: 889, lead: [{ mark: true, us: 889 }], setIsMark: false }, tail: { items: [{ copy: 'full' }, { words: [-32767, -32767, -24255] }, { copy: 'full' }, { words: [-32767, -32767, -24255] }, { copy: 'full' }, { words: [-32767, -32767, -24255, -1, 0] }] }, tailExact: 51, held: { items: [{ copy: 'full' }, { words: [-32767, -32767, -24255, -1, 0] }] }, heldExact: 40, heldOf: 40, codes: 51, exact: 51, spread: 0, source: 'compiled' },
  { family: 'Galaxis 16 Bit Quad Toggle', periodNs: 27777, quad: { firstMark: 415, mark: 160, spaces: [275, 445, 610, 775], digits: [8, 1, 7], gap: [32767, 32767, 26716] }, codes: 48, exact: 48, spread: 0, source: 'compiled' },
  { family: 'JerroldO1 16 Bit', periodNs: 26315, header: [9000, 4520], flat: 495, zero: 2250, one: 4505, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [495] }, { pad: 0 }, { words: [9020, -2250, 495, -87236] }], total: 199001 }, tailExact: 47, held: { items: [{ words: [9020, -2250, 495, -87236] }] }, heldExact: 37, heldOf: 37, codes: 47, exact: 47, spread: 0, source: 'compiled' },
  { family: 'Samsung 16 and 20 Bit', periodNs: 26315, header: [4500, 4480], flat: 495, zero: 500, one: 1495, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [495, -4495] }, { copy: 'bare', at: 1 }, { words: [495, -57501] }] }, tailExact: 36, held: { items: [{ copy: 'full' }, { words: [495, -4495] }, { copy: 'bare', at: 1 }, { words: [495, -57501] }] }, heldExact: 34, heldOf: 44, codes: 46, exact: 46, spread: 0, source: 'compiled' },
  { family: 'Philips Hurd 16 Bit LongToggle', periodNs: 27777, longToggle: { leader: [2662, 870], head: { mark: 468, space: 433, bits: 4 }, toggle: 867, data: { first: 440, second: 457, bits: 16 }, gap: [32767, 32767, 18866], copies: 3 }, codes: 46, exact: 46, spread: 0, source: 'compiled' },
  { family: 'Short 11 Bit 2', periodNs: 22727, header: [0, 0], flat: 228, zero: 8310, one: 5480, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [228] }, { pad: 0 }, { copy: 'full' }, { words: [228] }, { pad: 0 }, { copy: 'full' }, { words: [228] }, { pad: 1 }], total: 410236 }, tailExact: 42, held: { items: [{ copy: 'full' }, { words: [228] }, { pad: 0 }], total: 136746 }, heldExact: 31, heldOf: 31, codes: 42, exact: 42, spread: 0, source: 'compiled' },
  { family: 'PioneerO1 32 Bit Dual', periodNs: 25000, header: [8510, 4256], flat: 532, zero: 532, one: 1596, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [532, -35500] }, { copy: 'full', at: 1 }, { words: [532, -35500] }, { copy: 'full' }, { words: [532, -35500] }, { copy: 'full', at: 1 }, { words: [532, -35500] }, { copy: 'full' }, { words: [532, -35500] }, { copy: 'full', at: 1 }, { words: [532, -35501] }] }, tailExact: 40, held: { items: [{ copy: 'full' }, { words: [532, -35500] }, { copy: 'full', at: 1 }, { words: [532, -35501] }] }, heldExact: 39, heldOf: 39, codes: 40, exact: 40, spread: 0, source: 'compiled' },
  { family: 'MitsubishiO1 Dual 8 16 Bit', periodNs: 26315, header: [8400, 4250], flat: 510, zero: 570, one: 1600, carries: 'space', codes: 40, exact: 40, spread: 0, source: 'compiled' },
  { family: 'MemorexV2 32 Bit', periodNs: 26595, header: [9000, 4500], flat: 560, zero: 560, one: 1680, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [560, -39100] }, { copy: 'full' }, { words: [560, -39100] }, { copy: 'full' }, { words: [560, -39101] }] }, tailExact: 38, held: { items: [{ copy: 'full' }, { words: [560, -39101] }] }, heldExact: 37, heldOf: 37, codes: 38, exact: 38, spread: 0, source: 'compiled' },
  { family: 'Samsung 38 Bit', periodNs: 26315, header: [4490, 4473], flat: 490, zero: 504, one: 1477, carries: 'space', sections: [17, 21], sectionSpace: 4470, closing: 57928, codes: 35, exact: 35, spread: 0, source: 'compiled' },
  { family: 'Philips RECS80 11 Bit', periodNs: 26315, header: [0, 0], flat: 158, zero: 4902, one: 7442, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [158] }, { pad: 0 }, { copy: 'full' }, { words: [158] }, { pad: 0 }, { copy: 'full' }, { words: [158] }, { pad: 1 }], total: 364501 }, tailExact: 34, held: { items: [{ copy: 'full' }, { words: [158] }, { pad: 0 }], total: 121501 }, heldExact: 23, heldOf: 23, codes: 35, exact: 35, spread: 0, source: 'compiled' },
  { family: 'Pioneer 32 Bit Dual', periodNs: 25000, header: [8470, 4230], flat: 548, zero: 500, one: 1570, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25220] }, { copy: 'full' }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25220] }, { copy: 'full' }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25221] }] }, tailExact: 32, held: { items: [{ copy: 'full' }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25221] }] }, heldExact: 31, heldOf: 33, codes: 34, exact: 34, spread: 0, source: 'compiled' },
  { family: 'Videocrypt 11 Bit Toggle', periodNs: 30303, header: [0, 0], flat: 500, firstMark: 480, zero: 5282, one: 8150, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [500] }, { pad: 0 }, { copy: 'full' }, { words: [500] }, { pad: 0 }, { copy: 'full' }, { words: [500] }, { pad: 1 }], total: 413209 }, tailExact: 32, held: { items: [{ copy: 'full' }, { words: [500] }, { pad: 0 }], total: 137737 }, heldExact: 20, heldOf: 20, codes: 32, exact: 32, spread: 0, source: 'compiled' },
  { family: 'Roku 32 Bit 1', periodNs: 26315, header: [9000, 4500], flat: 562, zero: 562, one: 1688, carries: 'space', codes: 24, exact: 24, spread: 0, source: 'corpus', heardAs: 'MemorexO1 32 Bit' },
  { family: 'Pioneer 32 Bit', periodNs: 25000, header: [8470, 4230], flat: 548, zero: 500, one: 1570, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [548, -25220] }, { copy: 'full' }, { words: [548, -25220] }, { copy: 'full' }, { words: [548, -25221] }] }, tailExact: 9, held: { items: [{ copy: 'full' }, { words: [548, -25221] }] }, heldExact: 8, heldOf: 13, codes: 19, exact: 19, spread: 0, source: 'both' },
  { family: 'PanasonicV2 48 Bit', periodNs: 27472, header: [3480, 1730], flat: 425, zero: 450, one: 1320, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [425, -74800] }, { copy: 'full' }, { words: [425, -74800] }, { copy: 'full' }, { words: [425, -74801] }] }, tailExact: 12, held: { items: [{ copy: 'full' }, { words: [425, -74801] }] }, heldExact: 7, heldOf: 7, codes: 16, exact: 16, spread: 0, source: 'both', heardAs: 'SharpO1 48 Bit' },
  { family: 'Sony 20 Bit', periodNs: 25000, header: [2400, 600], flat: 600, zero: 600, one: 1200, carries: 'mark', framePeriod: 45000, tail: { items: [{ copy: 'full' }, { pad: 0 }, { copy: 'full' }, { pad: 0 }, { copy: 'full' }, { pad: 1 }], total: 135001 }, tailExact: 14, held: { items: [{ copy: 'full' }, { pad: 0 }], total: 45001 }, heldExact: 14, heldOf: 14, codes: 14, exact: 14, spread: 0, source: 'compiled' },
  { family: 'Sony 15 Bit', periodNs: 25000, header: [2400, 600], flat: 600, zero: 600, one: 1200, carries: 'mark', framePeriod: 45000, tail: { items: [{ copy: 'full' }, { pad: 0 }, { copy: 'full' }, { pad: 0 }, { copy: 'full' }, { pad: 1 }], total: 135001 }, tailExact: 12, held: { items: [{ copy: 'full' }, { pad: 0 }], total: 45001 }, heldExact: 11, heldOf: 11, codes: 12, exact: 12, spread: 0, source: 'both' },
  { family: 'Memorex 32 Bit', periodNs: 26315, header: [9000, 4500], flat: 600, zero: 500, one: 1600, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [600, -43001] }] }, tailExact: 8, held: { items: [{ copy: 'full' }, { words: [600, -43001] }] }, heldExact: 8, heldOf: 8, codes: 8, exact: 8, spread: 0, source: 'compiled' },
  { family: 'PioneerO1 32 Bit', periodNs: 25000, header: [8510, 4256], flat: 532, zero: 532, one: 1596, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [532, -35500] }, { copy: 'full' }, { words: [532, -35500] }, { copy: 'full' }, { words: [532, -35501] }] }, tailExact: 7, held: { items: [{ copy: 'full' }, { words: [532, -35501] }] }, heldExact: 7, heldOf: 7, codes: 7, exact: 7, spread: 0, source: 'compiled' },
  { family: 'MemorexO1 32 Bit', periodNs: 26315, header: [9000, 4500], flat: 560, zero: 560, one: 1690, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [560, -35101] }] }, tailExact: 3, held: { items: [{ copy: 'full' }, { words: [560, -35101] }] }, heldExact: 2, heldOf: 2, codes: 3, exact: 3, spread: 0, source: 'corpus' },
  { family: 'Pioneer 32 Bit 2', periodNs: 25000, header: [8470, 4230], flat: 548, zero: 500, one: 1570, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25220] }, { copy: 'full', at: 1 }, { words: [548, -25221] }] }, tailExact: 3, held: { items: [{ copy: 'full', at: 1 }, { words: [548, -25221] }] }, heldExact: 3, heldOf: 3, codes: 3, exact: 3, spread: 0, source: 'compiled' },
  { family: 'MemorexV2 32 Bit Dual', periodNs: 26315, header: [9000, 4500], flat: 560, oneMark: 594, zero: 594, one: 1725, carries: 'space', tail: { items: [{ copy: 'full' }, { words: [594, -33580] }, { copy: 'full', at: 1 }, { words: [594, -35740] }, { copy: 'full' }, { words: [594, -33580] }, { copy: 'full', at: 1 }, { words: [594, -35740] }, { copy: 'full' }, { words: [594, -33580] }, { copy: 'full', at: 1 }, { words: [594, -35741] }] }, tailExact: 2, held: { items: [{ copy: 'full' }, { words: [594, -33580] }, { copy: 'full', at: 1 }, { words: [594, -35741] }] }, heldExact: 2, heldOf: 2, codes: 2, exact: 2, spread: 0, source: 'compiled' },
  { family: 'Panasonic 16 Bit', periodNs: 26315, header: [0, 0], flat: 521, oneMark: 525, zero: 1575, one: 527, carries: 'space', codes: 1, exact: 1, spread: 0, source: 'compiled' },
  { family: 'Sharp 48 Bit', periodNs: 26455, header: [3367, 1720], flat: 410, oneMark: 409, zero: 434, one: 1304, carries: 'space', codes: 1, exact: 1, spread: 0, source: 'compiled' },
];
