/**
 * The golden vector shape, which is a contract between this package and the Python parser.
 *
 * It lives in its own module because it is the one function here that has to reach every reader: the
 * container, the key table and, since section 139, the infrared header. `gspm.ts` cannot import
 * `ir.ts`, which imports it, so a summary that grows a second subsystem belongs above both rather
 * than inside one of them.
 */
import {
  irBlockLength,
  irGroupCount,
  irGroups,
  irHeaderLength,
  irRecordBlocks,
  irRegion,
} from './ir.ts';
import type { Container } from './gspm.ts';

/**
 * The container as a plain object, the same shape `tools/gspm_parse.py --json` emits.
 *
 * That shape is the golden vector format, which is why the field names are snake_case here and
 * camelCase everywhere else: the vector is generated by the Python parser and read back by both,
 * so the JSON is a contract between the two rather than this package's own idiom.
 *
 * Pointer array entries are counted rather than listed, because the largest array seen holds
 * 8037 of them and would bury everything else.
 */
export function summary(c: Container): Record<string, unknown> {
  return {
    blob_offset: c.blobOffset,
    length: c.length,
    flash_base: c.flashBase,
    end_addr: c.endAddr,
    format_version: c.formatVersion,
    format_raw: c.formatRaw,
    pointer_count: c.pointerCount,
    architecture: c.architecture ?? null,
    version_word: c.versionWord ?? null,
    frame_length: c.frameLength ?? null,
    built_at: c.builtAt ?? null,
    trailer_checksum: c.trailerChecksum,
    checks: c.checks,
    sections: c.sections.map((s) => {
      const entries = c.pointerArray(s.slot);
      return {
        slot: s.slot,
        address: s.address,
        spare: s.spare,
        blob_offset: c.blobOffsetOf(s.address) ?? null,
        file_offset: c.fileOffset(s.address) ?? null,
        length: c.sectionLength(s.slot) ?? null,
        pointer_array_entries: entries === undefined ? null : entries.length,
      };
    }),
    keys: c.keys.map((k) => ({
      i: k.indexInTable,
      code: k.eventCode,
      index: k.index,
      flags: k.flags,
      event: k.eventName,
      scan: k.scanCode,
    })),
    ir: irSummary(c),
  };
}

/**
 * The infrared reading as a handful of totals, or null where there is no database.
 *
 * Deliberately including the two sums: a count of groups and blocks would agree between two
 * implementations that both read the wrong pointer, whereas the sum of the block lengths and the sum
 * of the framed bit counts cannot.
 */
function irSummary(c: Container): Record<string, unknown> | null {
  const groups = irGroups(c);
  if (groups === undefined) return null;
  const records = groups.flatMap((g) => g.addresses);
  const blocks = new Map<number, number>();
  let pointers = 0;
  let headerBytes = 0;
  const groupCounts: Record<string, number> = {};
  for (const address of records) {
    const found = irRecordBlocks(c, address);
    pointers += found.length;
    headerBytes += irHeaderLength(c, address);
    const key = String(irGroupCount(c, address));
    groupCounts[key] = (groupCounts[key] ?? 0) + 1;
    for (const block of found) {
      const length = irBlockLength(c, block);
      if (length !== undefined) blocks.set(block, length);
    }
  }
  let blockBytes = 0;
  for (const length of blocks.values()) blockBytes += length;
  return {
    groups: groups.length,
    records: records.length,
    group_counts: groupCounts,
    pointers,
    distinct_blocks: blocks.size,
    block_bytes: blockBytes,
    header_bytes: headerBytes,
    // Both ends of the record area. **Added because the two implementations had diverged here and
    // nothing compared them**: `ir_region` in Python has used `ir_header_length` since the flat 21 was
    // corrected, and this one still added the constant, so its top was nine bytes short wherever the
    // highest header declared two groups. Section 139 entry 15.
    region: irRegion(c) ?? null,
    // **No frame count here, and that is the finding rather than an omission.** The frame was in this
    // object for an hour and the vector immediately caught the two implementations disagreeing about
    // 37 records of one arch 8 (Harmony 880) config, because Python had grown a second decoder that
    // assumed pulse distance where `irframe.ts` tries both conventions and refuses a record reading as
    // neither. The Python one is gone, so there is one decoder and nothing to compare it against.
    // Section 139.
  };
}
