#!/usr/bin/env python3
"""
Golden vectors: what the Python parser says about each sample, for the TypeScript port to match.

The port is only provably equivalent if both parsers read the same bytes and produce the same
answer. Two suites of tests that happen to agree do not establish that, because each was written
from the same understanding and can be wrong in the same way. A vector generated by one and
asserted by the other is a real comparison.

The vectors live in the lab directory rather than in the repository, and that is a policy
decision rather than a convenience: a vector states section addresses and sizes for somebody's
actual configuration, which is derived from a private dump. Publishing a checksum is fine,
publishing a structural map of a stranger's remote is not.

    tools/golden.py --write        generate or refresh every vector
    tools/golden.py               compare, and exit non zero on any difference

Both suites read the vectors and skip cleanly when they are absent, the same contract as every
other image-backed test here.
"""
import json
import os
import sys

import _bootstrap  # noqa: F401

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tests'))

import lab  # noqa: E402
from harmony import gspm  # noqa: E402

# The samples that hold a container. Deliberately including the three that are not somebody's
# configuration (the factory config inside a firmware image, and two safe mode configs), because
# an implementation can agree on the ordinary cases and diverge on the degenerate ones: the empty
# 0xFEED frame only occurs in a safe mode config.
CONTAINERS = (
    'one_safemode', 'one34_region2', 'h700_gspm', 'h600_safemode_gspm', 'h650_safemode_gspm',
    'one_config', 'one_config_unprogrammed', 'h600_config',
    'h700_config', 'h700_config_2', 'h525_config', 'h525_config_2',
    'arch8_config_a', 'arch8_config_b', 'arch8_config_c', 'arch8_config_d',
    # The arch 9 safe mode container. It is in the corpus as a sample and out of the corpus wide
    # claim lists, section 78, and a golden vector is exactly the thing it should have: the two
    # implementations have to agree about the container that disagrees with everything else.
    'h525_safemode_ahcm',
    # The same arch 9 safe mode container, still **inside** the 64 KiB external firmware region it
    # was cut out of, at blob offset 0x8000. Its vector is a duplicate of the one above, deliberately
    # and for a third reason beyond the two given below: it is what checks that the cut was made in
    # the right place, since the in situ parse and the cut out parse have to agree about the base,
    # the end address and every check. They do. Section 118.
    'h525_external_firmware',
    # The section 58 pair. The first is byte identical to `one_config_unprogrammed`, so its vector
    # is a duplicate on purpose: the alternative is a special case in the test that asserts every
    # container sample has one, and a special case there is worth less than a duplicate file.
    'one_spare_before_sync', 'one_spare_after_sync',
    # And the third state of that unit, section 155: a real five device setup built by MyHarmony from
    # an account we can query. A golden vector is worth most exactly where the answer is known.
    'one_spare_myharmony',
    # And the fourth state of that unit, read on 30 August 2026 because the write rehearsal refused
    # against all three above: the remote holds a configuration none of them matches. Its own value
    # to this comparison is base slot 16, which it populates, making it the first sample **read off a
    # remote** where the two implementations of that reader are compared at all; the three that
    # populated it before were files the live service compiled and handed over.
    'one_spare_20260830',
    # And the same unit read again after the first write, section 222. Its vector is expected to
    # duplicate the one above exactly, which is the claim rather than an accident: the write put the
    # unit's own bytes back, so a differing vector would mean the configuration changed.
    'one_spare_after_first_write',
    # And the same unit again, after the first write that **changed** something, section 236. Its
    # vector is byte identical to the two above and that is the claim, not a disappointment: the
    # write changed two operands inside an action list, which no field a golden vector carries
    # reaches, so a **difference** here would mean the write moved something structural. The two
    # changed numbers are checked where they live, against the read back, and not here. Written
    # after generating it, because the first version of this comment predicted a difference.
    'one_spare_20260901_delay',
    # And after the second one, which is the state the revert started from. Its vector differs from
    # the row above in nothing a vector carries, for the same reason: what changed is an operand
    # inside an action list.
    'one_spare_20260901_denon',
    # The two configs Logitech compiled to a specification we wrote, section 132. They are out of the
    # corpus wide claim lists, deliberately, and they belong here for the same reason the arch 9 safe
    # mode container does: a golden vector is a cheap check between two implementations and costs the
    # published totals nothing. These two also happen to be the only samples whose devices and
    # activities were chosen before the bytes existed, so a disagreement between Python and TypeScript
    # about them would be a disagreement about a known answer.
    'calibration_one', 'calibration_h600',
    # The third, and the first config anywhere to populate base slot 16. Its vector is the only one
    # whose `number_senders` is not an empty list, so it is the only place the two implementations of
    # that reader are compared at all. Section 154.
    'calibration_favchannels',
    # The fourth, and the second to populate base slot 16, from the other test account. Its value
    # is the structure beside the record rather than the record: two of its five favourites do not
    # use base slot 16 at all, so the vector compares the two implementations on the action lists
    # and state transitions that spell a channel out instead. Section 156.
    'calibration_favzero',
    # The fifth, 24 August 2026, and the largest sample anywhere here: fifteen appliances chosen so
    # that every protocol family in Logitech's catalogue the corpus could not settle appears in it.
    # Eighteen of the rhythm table's entries are measured off this one file, so a disagreement between
    # the two implementations about it is a disagreement about the table. Section 165.
    'compiled_protocols',
    'compiled_protocols_2',
    'compiled_protocols_3',
    # The phase 7 pair, section 174: the calibration account compiled without and with the
    # television the composer adds. The after container is the one the composer is compared to.
    'phase7_before', 'phase7_after',
    # The Harmony 350, arch 16, read with concordance on 27 August 2026 since this project's own
    # transport does not reach the file based family, section 193. It belongs here and **not** in
    # `lab.CONTAINERS`: this list is every sample that parses, which is what makes the two codecs
    # comparable on a new architecture, where that one is what every corpus wide total is computed
    # from. Section 194 came out of comparing it, so excluding it would have left the corpus
    # agreeing with itself about a field only a sixth architecture could contradict.
    'h350_config',
    # The arch 8 safe mode container, which is **inside** the firmware image rather than in a file
    # of its own: `gspm.parse` finds it at blob offset 0xE000, flash 0x01E000, and every check
    # passes. The two images carry it identically, since they differ only in the skin byte, so the
    # second vector is a duplicate for the same reason the sync pair's first one is. Section 114.
    'arch8_code_880', 'arch8_code_885',
    # An 885 user config, the sample that settles which way arch 8 encodes a skin, and the first
    # arch 10 container: 23 pointer slots and format 1.7, so four of its checks fail and the vector
    # records that rather than hiding it. Sections 113 and 115.
    'arch8_config_880', 'arch8_config_885', 'h895_config', 'h890_config',
    # The second 890, whose vector records a container that disagrees with itself: five of its
    # eleven checks fail, including `end_addr_points_at_end_marker`, which no input could fail
    # before section 117. Both implementations have to agree about that too, and they have to agree
    # about the base the clock anchor recovers where the marker subtraction got it wrong.
    'h890_config_2',
    # Two second reads of the 890s, section 122. The good one is a control and the bad one is the
    # reason to cross check: it defeats the anchor, so both codecs have to agree about what the
    # fallback then returns, and a divergence there would be invisible in every other test.
    'h890_config_rescan',
    'h890_config_2_rescan',
    'h890_config_2_redump_1',
    'h890_config_2_redump_2',
    'h890_config_2_redump_3',
    # The two regions Logitech's own client read off the spare Harmony One, section 215. **Both are
    # here, including the duplicate**, and that is deliberately the opposite of what
    # `PARSEABLE_EXCLUDED` does with the same pair, because the two populations are asked different
    # questions. A corpus wide total is distorted by counting one config twice; a golden vector is a
    # comparison between two implementations, where a duplicate costs one file and a special case in
    # `test_the_vector_list_covers_every_container_in_the_corpus` costs more. That trade was already
    # made here for `one_spare_before_sync`, whose vector duplicates `one_config_unprogrammed`'s, and
    # this follows it rather than reopening it.
    #
    # The user config's vector is therefore expected to match `one_spare_before_sync`'s exactly, which
    # is itself worth having: it is the two implementations agreeing that a container read out of a
    # 3932160 byte region is the same container as one read as a trimmed file.
    'vendor_region_user_config',
    # And the embedded config, which turned out to be a duplicate too, of `one_safemode`: same 8902
    # byte body, same 22 sections, differing only in where the container sits in its file. Its vector
    # is worth keeping for exactly that reason, since the two arrived by routes with nothing in
    # common, one cut out of a firmware image and one read off a different unit by Logitech's own
    # client. Section 215, where the claim that it had no counterpart is corrected.
    'vendor_region_embedded_config',
)


def directory():
    """Where the vectors live, or None when there is no lab directory at all."""
    return os.path.join(lab.LAB, 'golden') if lab.LAB else None


def vector_path(name):
    d = directory()
    return None if d is None else os.path.join(d, '%s.json' % name)


def generate(name):
    """The vector for one sample, or None when its image is not available.

    Parses the file exactly as it sits on disk, rather than unwrapping an EZHex header first.
    That is on purpose: it makes `blob_offset` and every `file_offset` part of the comparison,
    and confusing a blob offset with a file offset is a mistake that has already cost time here.
    """
    path = lab.path(name)
    if not path:
        return None
    with open(path, 'rb') as fh:
        return gspm.summary(gspm.parse(fh.read()))


def main():
    write = '--write' in sys.argv
    d = directory()
    if d is None:
        print('no lab directory found; set HARMONY_LAB', file=sys.stderr)
        return 2
    if write:
        os.makedirs(d, exist_ok=True)

    missing, written, same, differ = [], [], [], []
    for name in CONTAINERS:
        current = generate(name)
        if current is None:
            missing.append(name)
            continue
        path = vector_path(name)
        if write:
            with open(path, 'w') as fh:
                json.dump(current, fh, indent=2, sort_keys=True)
                fh.write('\n')
            written.append(name)
            continue
        if not os.path.exists(path):
            missing.append(name + ' (no vector)')
            continue
        with open(path) as fh:
            stored = json.load(fh)
        (same if stored == current else differ).append(name)

    for name in differ:
        print('DIFFERS: %s' % name)
    print('%s: %d written, %d match, %d differ, %d unavailable'
          % (d, len(written), len(same), len(differ), len(missing)))
    if missing:
        print('unavailable: %s' % ', '.join(missing))
    return 1 if differ else 0


if __name__ == '__main__':
    sys.exit(main())
