#!/usr/bin/env python3
"""
Golden vectors: what the Python parser says about each sample, for the TypeScript port to match.

The port is only provably equivalent if both parsers read the same bytes and produce the same
answer. Two suites of tests that happen to agree do not establish that, because each was written
from the same understanding and can be wrong in the same way. A vector generated by one and
asserted by the other is a real comparison.

The vectors live in the lab directory rather than in the repository, and that is a policy
decision rather than a convenience: a vector states section addresses and sizes for somebody's
actual configuration, which is derived from a private dump. Publishing a checksum is fine,
publishing a structural map of a stranger's remote is not.

    tools/golden.py --write        generate or refresh every vector
    tools/golden.py               compare, and exit non zero on any difference

Both suites read the vectors and skip cleanly when they are absent, the same contract as every
other image-backed test here.
"""
import json
import os
import sys

import _bootstrap  # noqa: F401

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tests'))

import lab  # noqa: E402
from harmony import gspm  # noqa: E402

# The samples that hold a container. Deliberately including the three that are not somebody's
# configuration (the factory config inside a firmware image, and two safe mode configs), because
# an implementation can agree on the ordinary cases and diverge on the degenerate ones: the empty
# 0xFEED frame only occurs in a safe mode config.
CONTAINERS = (
    'one_safemode', 'one34_region2', 'h700_gspm', 'h600_safemode_gspm', 'h650_safemode_gspm',
    'one_config', 'one_config_unprogrammed', 'h600_config',
    'h700_config', 'h700_config_2', 'h525_config', 'h525_config_2',
    'arch8_config_a', 'arch8_config_b', 'arch8_config_c', 'arch8_config_d',
    # The section 58 pair. The first is byte identical to `one_config_unprogrammed`, so its vector
    # is a duplicate on purpose: the alternative is a special case in the test that asserts every
    # container sample has one, and a special case there is worth less than a duplicate file.
    'one_spare_before_sync', 'one_spare_after_sync',
)


def directory():
    """Where the vectors live, or None when there is no lab directory at all."""
    return os.path.join(lab.LAB, 'golden') if lab.LAB else None


def vector_path(name):
    d = directory()
    return None if d is None else os.path.join(d, '%s.json' % name)


def generate(name):
    """The vector for one sample, or None when its image is not available.

    Parses the file exactly as it sits on disk, rather than unwrapping an EZHex header first.
    That is on purpose: it makes `blob_offset` and every `file_offset` part of the comparison,
    and confusing a blob offset with a file offset is a mistake that has already cost time here.
    """
    path = lab.path(name)
    if not path:
        return None
    with open(path, 'rb') as fh:
        return gspm.summary(gspm.parse(fh.read()))


def main():
    write = '--write' in sys.argv
    d = directory()
    if d is None:
        print('no lab directory found; set HARMONY_LAB', file=sys.stderr)
        return 2
    if write:
        os.makedirs(d, exist_ok=True)

    missing, written, same, differ = [], [], [], []
    for name in CONTAINERS:
        current = generate(name)
        if current is None:
            missing.append(name)
            continue
        path = vector_path(name)
        if write:
            with open(path, 'w') as fh:
                json.dump(current, fh, indent=2, sort_keys=True)
                fh.write('\n')
            written.append(name)
            continue
        if not os.path.exists(path):
            missing.append(name + ' (no vector)')
            continue
        with open(path) as fh:
            stored = json.load(fh)
        (same if stored == current else differ).append(name)

    for name in differ:
        print('DIFFERS: %s' % name)
    print('%s: %d written, %d match, %d differ, %d unavailable'
          % (d, len(written), len(same), len(differ), len(missing)))
    if missing:
        print('unavailable: %s' % ', '.join(missing))
    return 1 if differ else 0


if __name__ == '__main__':
    sys.exit(main())
